# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MIST Guides
tagline:          'A GW2 guild for learning fractals.'
description:      'A friendly place for getting started with fractals to learning the most difficult of CMs and everything in between'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jordan (Canadians360)'
  url:            https://twitter.com/canadians360

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
